In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df=pd.read_excel("/content/data_final.xlsx")

In [31]:
df.head()

,JENIS_NASABAH,STATUS_RUMAH_TINGGAL,LAMA_DITEMPATI,USIA,PENDIDIKAN_TERAKHIR,PEKERJAAN,STATUS_PEKERJAAN,SUMBER_DANA,PENGHASILAN,STATUS_PENGAJUAN
0,Nasabah Baru,Sewa/Kontrak,2.0,23,S1,Wiraswasta,Kontrak,Gaji,4100000,Diterima
1,Nasabah Baru,Milik Keluarga,8.0,33,D3/SM,Wiraswasta,Tetap,Gaji,4200000,Ditolak
2,Nasabah Baru,Milik Keluarga,6.0,23,SMA,Ibu Rumah,Tetap,Hasil Usaha,3800000,Diterima
3,Nasabah Baru,Milik Keluarga,4.0,34,SMA,Wiraswasta,Tetap,Gaji,3050000,Diterima
4,Nasabah Baru,Milik Keluarga,5.0,41,S1,Pengusaha,Tetap,Hasil Usaha,4200000,Ditolak

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1220 entries, 0 to 1219
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   JENIS_NASABAH          1220 non-null   object
 1   STATUS_RUMAH_TINGGAL   1220 non-null   object
 2   LAMA_DITEMPATI         1220 non-null   float64
 3   USIA                   1220 non-null   int64
 4   PENDIDIKAN_TERAKHIR    1220 non-null   object
 5   PEKERJAAN              1220 non-null   object
 6   STATUS_PEKERJAAN       1220 non-null   object
 7   SUMBER_DANA            1220 non-null   object
 8   PENGHASILAN            1220 non-null   int64
 9   STATUS_PENGAJUAN       1220 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 95.4+ KB

In [33]:
df.describe()

       LAMA_DITEMPATI        USIA   PENGHASILAN
count     1220.000000  1220.000000  1.220000e+03
mean         5.884016    31.440984  4.282527e+06
std          3.708684     7.248702  1.489665e+06
min          1.000000    21.000000  1.700000e+06
25%          4.000000    25.000000  3.500000e+06
50%          5.000000    31.000000  4.000000e+06
75%          8.000000    36.000000  4.400000e+06
max         63.000000    53.000000  8.500000e+06

In [34]:
df.describe(include=object)

,JENIS_NASABAH,STATUS_RUMAH_TINGGAL,PENDIDIKAN_TERAKHIR,PEKERJAAN,STATUS_PEKERJAAN,SUMBER_DANA,STATUS_PENGAJUAN
count,1220,1220,1220,1220,1220,1220,1220
unique,4,5,7,17,2,2,2
top,Nasabah Baru,Milik Keluarga,SMA,Wiraswasta,Tetap,Gaji,Diterima
freq,897,899,575,298,1035,981,685

In [35]:
# Package untuk cleaning, modelling, dan evaluation model
import statsmodels.api as sm
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [36]:
kategori = ['JENIS_NASABAH',	'STATUS_RUMAH_TINGGAL', 'PENDIDIKAN_TERAKHIR', 'PEKERJAAN', 'STATUS_PEKERJAAN', 'SUMBER_DANA', 'STATUS_PENGAJUAN']

In [37]:
df_cat = df[kategori]
df_cat.head()

KeyError: "None of [Index(['JENIS_NASABAH', 'STATUS_RUMAH_TINGGAL', 'PENDIDIKAN_TERAKHIR',\n       'PEKERJAAN', 'STATUS_PEKERJAAN', 'SUMBER_DANA', 'STATUS_PENGAJUAN'],\n      dtype='object')] are in the [columns]"

In [ ]:
# Ubah kedalam bentuk numerik
encoded_data = LabelEncoder()

for feature in kategori:
        if feature in df.columns.values:
            df[feature] = encoded_data.fit_transform(df[feature])

df.head()